name: "📌 New Task / Feature Request"
description: "Create a new task or request a new feature"
title: "[Feature] <Task or Feature Name>"
labels: ["enhancement", "feature request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "## 🔹 Description\nPlease provide details about the task or feature request."

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Describe the task or feature you want to add."
      placeholder: "Include goals, expected functionality, or any relevant details."
    validations:
      required: true

  - type: checkboxes
    id: work_area
    attributes:
      label: "🛠 Work Area"
      description: "Select the area(s) where this task or feature applies."
      options:
        - label: "Frontend"
        - label: "Backend"
        - label: "Both Frontend & Backend"

  - type: textarea
    id: tech-stack
    attributes:
      label: "🔧 Related Technologies"
      description: "List the technologies involved in this task or feature."
      placeholder: "Example: JavaScript, Node.js, Express, Bootstrap, MongoDB, etc."

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ Acceptance Criteria"
      description: "Define the conditions under which this task is considered complete."
      placeholder: "This task is complete when..."

  - type: textarea
    id: timeline
    attributes:
      label: "⏳ Estimated Timeline"
      description: "Specify the estimated time required for this task (if applicable)."
      placeholder: "Example: 1 week, 2 weeks, etc."

  - type: textarea
    id: additional-info
    attributes:
      label: "📌 Additional Information"
      description: "Include any additional notes or references related to this task (if applicable)."
      placeholder: "For example, API references, design mockups, related documentation, etc."
