name: "📌 Feature Request"
description: "Create a new request a new feature"
title: "Feature/"
labels: ["enhancement", "feature request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "## 🔹 Description\nPlease provide details about the task or feature request."

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Describe the feature you want to add."
      placeholder: "Include goals, expected functionality, or any relevant details."
    validations:
      required: true

  - type: checkboxes
    id: work_area
    attributes:
      label: "🛠 Work Area"
      description: "Select the area(s) where this task or feature applies."
      options:
        - label: "Frontend"
        - label: "Backend"



